### ISSUE TITLE
 cannot import name 'FeatureLoader' from 'sae_auto_interp.features'

### ISSUE THREAD

**Issue by kernel-loophole** [EleutherAI/sae-auto-interp#30]
while trying to run this ```https://github.com/EleutherAI/sae-auto-interp/blob/main/demo/simulate.py```  script got this error ImportError: cannot import name 'FeatureLoader' from 'sae_auto_interp.features'.i also check that there is no class named FeatureLoader in features.py.
checkout this colab notebook for more details https://colab.research.google.com/drive/1qX2USmeCPyFksARj0ipWVk-aYScr1uCn?usp=sharing

**Comment by SrGonao** [comment]
Hi. I updated the script with the required changes for it to run, but as the header of the script said, this script had still not updated to the most recent changes we made to the library and might not be completely functional. Is there a reason you want to start with simulation instead of using the basic.py script?

**Comment by kernel-loophole** [comment]
@SrGonao I've trained a sparse autoencoder and have a bunch of weights for this. I'd like to run this through the Eleuther auto-interp

**Comment by SrGonao** [comment]
The basic.py demo is the best place to start.

**Comment by kernel-loophole** [comment]
okay that's great
